0 CONSTANT EOF
1 CONSTANT INT
2 CONSTANT ADD
3 CONSTANT SUB
4 CONSTANT MUL
5 CONSTANT DIV
6 CONSTANT LPAREN
7 CONSTANT RPAREN

VARIABLE chr
: CHR@ chr c@ ;
: CHR! chr c! ;
: CHR= CHR@ = ;
: VAL CHR@ '0' - ;

: ERROR ( -- )
    ." Error parsing input" CR ABORT ;

: ISDIGIT ( char -- bool )
    CHR@ '0' '9' 1+ WITHIN ;

: ISWHITESPACE ( -- bool)
    9 CHR= 32 CHR= OR ;

: ADVANCE ( -- )
    KEY DUP CHR! EMIT ;

: SKIPWHITESPACE ( -- )
    BEGIN
        ISWHITESPACE WHILE
        ADVANCE
    REPEAT ;

: GETINT
    0
    BEGIN
        ISDIGIT WHILE
        10 * VAL +
        ADVANCE
    REPEAT
    INT ;

DEFER _TOKEN

: GETCHAR
    CHR@ CASE
        9 OF SKIPWHITESPACE _TOKEN ENDOF
        13 OF EOF ENDOF
        32 OF SKIPWHITESPACE _TOKEN ENDOF
        '+' OF ADVANCE ADD ENDOF
        '-' OF ADVANCE SUB ENDOF
        '*' OF ADVANCE MUL ENDOF
        '/' OF ADVANCE DIV ENDOF
        '(' OF ADVANCE LPAREN ENDOF
        ')' OF ADVANCE RPAREN ENDOF
    ENDCASE ;

: TOKEN
    RECURSIVE
    ISDIGIT
    IF GETINT
    ELSE GETCHAR
    ENDIF ;

' TOKEN IS _TOKEN

: ISTERMOP
    DUP MUL = IF -1 ELSE DUP DIV = ENDIF ;

: BINOP
    RECURSIVE
    CASE
        EOF OF ENDOF
        INT OF ENDOF
        ADD OF BINOP >R BINOP R> + ENDOF
        SUB OF BINOP >R BINOP R> - ENDOF
        MUL OF BINOP >R BINOP R> * ENDOF
        DIV OF BINOP >R BINOP R> / ENDOF
    ENDCASE ;

DEFER _EXPR

: UNOP
    RECURSIVE
    CASE
        EOF OF ENDOF
        INT OF ENDOF
        ADD OF TOKEN UNOP ENDOF
        SUB OF TOKEN UNOP -1 * ENDOF
        LPAREN OF
            TOKEN _EXPR
            RPAREN =
            IF DROP
            ELSE ERROR
            ENDIF
        ENDOF
    ENDCASE ;

\ factor : (ADD|SUB)factor | INTEGER | LPAREN expr RPAREN
: FACTOR
    CASE
        EOF OF EOF ENDOF
        INT OF INT TOKEN ENDOF
        ADD OF ADD UNOP INT TOKEN ENDOF
        SUB OF SUB UNOP INT TOKEN ENDOF
        LPAREN OF
            TOKEN _EXPR
            RPAREN =
            IF TOKEN
            ELSE ERROR
            ENDIF
        ENDOF
    ENDCASE ;

: MULOP
    RECURSIVE
    CASE
        EOF OF MULOP EOF ENDOF
        INT OF INT MUL BINOP INT ENDOF
        MUL OF MUL BINOP INT MUL ENDOF
        DIV OF MUL BINOP INT DIV ENDOF
        ADD OF MUL BINOP INT ADD ENDOF
        SUB OF MUL BINOP INT SUB ENDOF
        RPAREN OF MULOP RPAREN ENDOF
    ENDCASE ;

: DIVOP
    RECURSIVE
    CASE
        EOF OF DIVOP EOF ENDOF
        INT OF INT DIV BINOP INT ENDOF
        MUL OF DIV BINOP INT MUL ENDOF
        DIV OF DIV BINOP INT DIV ENDOF
        ADD OF DIV BINOP INT ADD ENDOF
        SUB OF DIV BINOP INT SUB ENDOF
        RPAREN OF DIVOP RPAREN ENDOF
    ENDCASE ;

: TERMOP
    CASE
        MUL OF TOKEN FACTOR MULOP ENDOF
        DIV OF TOKEN FACTOR DIVOP ENDOF
    ENDCASE ;

\ term : factor ((MUL | DIV) factor)*
: TERM
    FACTOR
    BEGIN
        ISTERMOP WHILE
        TERMOP
    REPEAT ;

: ISEXPROP
    DUP ADD = IF -1 ELSE DUP SUB = ENDIF ;

: ADDOP
    RECURSIVE
    CASE
        EOF OF ADDOP EOF ENDOF
        INT OF INT ADD BINOP INT ENDOF
        ADD OF ADD BINOP INT ADD ENDOF
        SUB OF ADD BINOP INT SUB ENDOF
        RPAREN OF ADDOP RPAREN ENDOF
    ENDCASE ;

: SUBOP
    RECURSIVE
    CASE
        EOF OF SUBOP EOF ENDOF
        INT OF INT SUB BINOP INT ENDOF
        ADD OF SUB BINOP INT ADD ENDOF
        SUB OF SUB BINOP INT SUB ENDOF
        RPAREN OF SUBOP RPAREN ENDOF
    ENDCASE ;

: EXPROP
    CASE
        ADD OF TOKEN TERM ADDOP ENDOF
        SUB OF TOKEN TERM SUBOP ENDOF
    ENDCASE ;

\ expr : term ((ADD | SUB) term)*
: EXPR
    TERM
    BEGIN
        ISEXPROP WHILE
        EXPROP
    REPEAT ;

' EXPR IS _EXPR

: MAIN
    CR
    ADVANCE TOKEN
    EXPR
    EOF =
    IF CR DROP .
    ELSE ERROR
    ENDIF ;
